repos:
  - repo: git://github.com/golangci/golangci-lint
    rev: v1.27.0
    hooks:
      - id: golangci-lint

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.1
    hooks:
      - id: markdownlint
